# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20170825_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='参数名称')),
                ('identifier', models.CharField(max_length=64, verbose_name='参数符号')),
                ('name_output', models.CharField(max_length=64, verbose_name='输出符号')),
                ('range_min', models.IntegerField(blank=True, null=True, verbose_name='量程最小值')),
                ('range_max', models.IntegerField(blank=True, null=True, verbose_name='量程最大值')),
                ('unit', models.CharField(blank=True, max_length=8, verbose_name='单位')),
                ('accuracy', models.IntegerField(blank=True, verbose_name='精度')),
                ('samplerate', models.IntegerField(verbose_name='采样率')),
                ('type', models.CharField(choices=[('数字量', '数字量'), ('模拟量', '模拟量'), ('开关量', '开关量')], max_length=8, verbose_name='参数类型')),
                ('source', models.CharField(choices=[('加装', '加装'), ('抽引', '抽引')], max_length=8, verbose_name='参数来源')),
                ('ground_monitor', models.BooleanField(verbose_name='地面监控')),
                ('airborne_monitor', models.BooleanField(verbose_name='机载监控')),
                ('system', models.CharField(max_length=16, verbose_name='系统/专业')),
                ('responsibility', models.CharField(max_length=16, verbose_name='负责方')),
                ('acquisitionInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.AcquisitionInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PositionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SchematicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SensorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_number', models.CharField(max_length=32, verbose_name='设备号')),
                ('part_number', models.CharField(max_length=32, verbose_name='型号')),
                ('name', models.CharField(max_length=32, verbose_name='传感器名称')),
                ('weight', models.IntegerField(verbose_name='重量')),
                ('voltage', models.CharField(max_length=32, verbose_name='供电要求')),
                ('power', models.IntegerField(verbose_name='功耗')),
                ('signal_range', models.IntegerField(verbose_name='输出信号范围')),
                ('signal_type', models.CharField(max_length=32, verbose_name='输出信号类型')),
                ('connector_type', models.CharField(max_length=32, verbose_name='接插件型号')),
                ('connector_match_type', models.CharField(max_length=32, verbose_name='配对接插件型号')),
                ('connector_number', models.CharField(max_length=32, verbose_name='接插件编号')),
                ('connector_type_temp', models.CharField(max_length=32, verbose_name='传感器连接器类型号')),
                ('sequence_number', models.CharField(max_length=2, verbose_name='顺序号')),
                ('wire_guage', models.CharField(max_length=16, verbose_name='线规')),
                ('wire_zhi', models.CharField(max_length=16, verbose_name='线制')),
                ('wire_sum', models.IntegerField(verbose_name='线缆数量')),
                ('pin_define', models.CharField(max_length=256, verbose_name='针脚定义')),
            ],
        ),
        migrations.CreateModel(
            name='SensorNumberInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(verbose_name='序列号')),
                ('EDZ_number', models.IntegerField(verbose_name='EDZ区域号')),
                ('part_number', models.CharField(max_length=32, verbose_name='传感器零件号')),
            ],
        ),
        migrations.CreateModel(
            name='SeparationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='parameter',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.PositionInfo'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='schematicInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.SchematicInfo'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='sensor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.SensorInfo'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='sensornumber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.SensorNumberInfo'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='separation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.SeparationInfo'),
        ),
    ]
