# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20180111_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='accuracy',
            field=models.CharField(blank=True, max_length=64, verbose_name='精度'),
        ),
    ]
