# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20180114_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='airborne_monitor',
            field=models.CharField(max_length=8, null=True, verbose_name='机载监控'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='ground_monitor',
            field=models.CharField(max_length=8, null=True, verbose_name='地面监控'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='range_max',
            field=models.FloatField(blank=True, null=True, verbose_name='量程最大值'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='range_min',
            field=models.FloatField(blank=True, null=True, verbose_name='量程最小值'),
        ),
    ]
