# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-08 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20180208_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='aircraftinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.AircraftInfo'),
        ),
    ]
