# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-08 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_parameter_aircraftinfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aircraftinfo',
            unique_together=set([('aircraft_model', 'aircraft_number')]),
        ),
    ]
