# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-11 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20180211_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='aircraft_model',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='aircraft_number',
        ),
    ]
