# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-22 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20180211_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='schematicInfo',
        ),
        migrations.RemoveField(
            model_name='sensorinfo',
            name='connector_match_type',
        ),
        migrations.RemoveField(
            model_name='sensorinfo',
            name='connector_number',
        ),
        migrations.RemoveField(
            model_name='sensorinfo',
            name='connector_type',
        ),
        migrations.RemoveField(
            model_name='sensorinfo',
            name='connector_type_temp',
        ),
        migrations.RemoveField(
            model_name='sensorinfo',
            name='pin_define',
        ),
        migrations.RemoveField(
            model_name='sensorinfo',
            name='sequence_number',
        ),
        migrations.AddField(
            model_name='parameter',
            name='status',
            field=models.CharField(choices=[('request_validating', '需求分析'), ('request_published', '需求发布'), ('sensor_published', '传感器选型发布'), ('acquisition_published', '测试采集发布')], default='request_validating', max_length=20, verbose_name='参数状态'),
        ),
    ]
