# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20180222_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirbornNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, verbose_name='装机件号')),
            ],
        ),
        migrations.RenameField(
            model_name='sensorinfo',
            old_name='name',
            new_name='sensor_name',
        ),
        migrations.RenameField(
            model_name='sensorinfo',
            old_name='part_number',
            new_name='sensor_type',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='sensornumber',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='separation',
        ),
        migrations.RemoveField(
            model_name='sensorinfo',
            name='equipment_number',
        ),
        migrations.RemoveField(
            model_name='sensorinfo',
            name='wire_guage',
        ),
        migrations.RemoveField(
            model_name='sensorinfo',
            name='wire_sum',
        ),
        migrations.RemoveField(
            model_name='sensorinfo',
            name='wire_zhi',
        ),
        migrations.AddField(
            model_name='sensorinfo',
            name='airborn_PN',
            field=models.CharField(max_length=32, null=True, verbose_name='装机件号'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='sensor_airborn_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.AirbornNumber'),
        ),
    ]
