# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20180223_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorinfo',
            name='airborn_PN',
        ),
    ]
