# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_remove_sensorinfo_airborn_pn'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorinfo',
            name='comment',
            field=models.CharField(max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sensorinfo',
            name='signal_range',
            field=models.CharField(max_length=16, verbose_name='输出信号范围'),
        ),
    ]
