# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20180223_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorInfoManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
