# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-23 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_sensorinfomanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorInfoManager',
        ),
    ]
