# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_delete_sensorinfomanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbornnumber',
            name='number',
            field=models.CharField(max_length=16, null=True, verbose_name='装机件号'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.SensorInfo'),
        ),
    ]
