# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-09 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20180309_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbornnumber',
            name='ATA',
            field=models.CharField(max_length=4, null=True, verbose_name='ATA章节号'),
        ),
        migrations.AddField(
            model_name='airbornnumber',
            name='aircraft_num',
            field=models.CharField(max_length=2, null=True, verbose_name='飞机架机号'),
        ),
        migrations.AddField(
            model_name='airbornnumber',
            name='aircraft_type',
            field=models.CharField(max_length=1, null=True, verbose_name='飞机型号'),
        ),
        migrations.AddField(
            model_name='airbornnumber',
            name='index',
            field=models.CharField(max_length=3, null=True, verbose_name='流水号'),
        ),
    ]
